//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bookCorner_dbContext : DbContext
    {
        public bookCorner_dbContext()
            : base("name=bookCorner_dbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autor> autor { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<editorial> editorial { get; set; }
        public virtual DbSet<editorial_libro> editorial_libro { get; set; }
        public virtual DbSet<lector> lector { get; set; }
        public virtual DbSet<lector_libro> lector_libro { get; set; }
        public virtual DbSet<libro> libro { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
