//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lector_libro
    {
        public int id { get; set; }
        public int id_lector { get; set; }
        public int id_libro { get; set; }
        public string resenya { get; set; }
        public Nullable<int> puntuacion { get; set; }
    
        public virtual lector lector { get; set; }
        public virtual libro libro { get; set; }
    }
}
